-- UKSFTA COP - Supabase Initialization Script

-- 1. Create Live Session Table
CREATE TABLE IF NOT EXISTS public.live_session (
    id bigint PRIMARY KEY,
    world_name text NOT NULL DEFAULT 'altis',
    last_updated timestamp with time zone DEFAULT now()
);

-- Initialize the master session row
INSERT INTO public.live_session (id, world_name) 
VALUES (1, 'altis') 
ON CONFLICT (id) DO NOTHING;

-- 2. Create Tactical Drawings Table
CREATE TABLE IF NOT EXISTS public.tactical_drawings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geojson jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Enable RLS (Optional but recommended)
ALTER TABLE public.live_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tactical_drawings ENABLE ROW LEVEL SECURITY;

-- 4. Set Public Permissions (Allow read-only access for COP viewers)
CREATE POLICY "Allow public read-only access to session" 
ON public.live_session FOR SELECT TO anon USING (true);

CREATE POLICY "Allow public read-only access to drawings" 
ON public.tactical_drawings FOR SELECT TO anon USING (true);

-- 5. Create Audit Logging Table
CREATE TABLE IF NOT EXISTS public.tactical_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    actor text NOT NULL DEFAULT 'SYSTEM',
    details text,
    created_at timestamp with time zone DEFAULT now()
);

-- Allow public read-only access to logs if needed for intelligence review
CREATE POLICY "Allow public read-only access to logs" 
ON public.tactical_logs FOR SELECT TO anon USING (true);
